/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class App_Aplicacion */

#ifndef _Included_App_Aplicacion
#define _Included_App_Aplicacion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     App_Aplicacion
 * Method:    ejecutarComandosGit
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_App_Aplicacion_ejecutarComandosGit
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
